version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_assessment_exercise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
  redis:
    image: 'redis:alpine'
  web:
    build: .
    volumes:
      - .:/code
    command: python /code/manage.py runserver 0.0.0.0:8000 --settings=${SETTINGS}
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
  celery:
    build: .
    volumes:
      - .:/code
    command: celery -A backend_assessment_exercise worker -l info&
    environment:
      - DJANGO_SETTINGS_MODULE=${SETTINGS}
    depends_on:
      - web
      - db
      - redis
  flower:
    build: .
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=${SETTINGS}
    ports:
      - "5555:5555"
    command: celery -A backend_assessment_exercise flower --address=0.0.0.0&
    depends_on:
      - celery
      - redis

