# Generated by Django 4.0.8 on 2022-10-18 20:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('hobbies', models.TextField(blank=True, verbose_name='hobbies')),
                ('validated_phone', models.BooleanField(default=False, verbose_name='validated phone')),
                ('validated_email', models.BooleanField(default=False, verbose_name='validated email')),
            ],
        ),
    ]
